name: flutter_application_2
description: "A JasTip prototype UI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  supabase_flutter: ^2.0.0
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

